config/routes.rb
Rails.application.routes.draw do
  root "bodies#index"

  resources :articles
  resources :bodies, only: %i[ index show new create destroy ]
  post '/body_symptoms/:side', to: 'bodies#body_symptoms', as: 'body_symptoms'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/body.rb
class Body < ApplicationRecord
  validates :parts, presence: false, parts: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/bodies_controller.rb
class BodiesController < ApplicationController
  def index
    @bodies = Body.all
  end

  def show
    @body = Body.find(params[:id])
  end

  def new
    @body = Body.new
  end

  def create
    @body = Body.new(body_params)

    if @body.save
      redirect_to "/"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def body_symptoms
    @side = params[:side]
    @link = link_params[:parts]
    respond_to do |format|
      format.turbo_stream
    end
  end

  def destroy
    @body = Body.find(params[:id])
    @body.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def body_params
    params.require(:body).permit(:parts)
  end

  def link_params
    params.permit(:parts, :side)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bodies_helper.rb
module BodiesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article %>
    </li>
  <% end %>
</ul>

<%= link_to "New Article", new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

app/views/bodies/body_symptoms.turbo_stream.erb
<%= turbo_stream.replace("body_symptoms_modal") do %>
  <div id="body_symptoms_modal" data-health-questionnaire-target="bodySymptomsModal" data-list="<%= @link %>" class="fixed top-0 left-0 w-full flex justify-center items-center">
    <p id="linkValue" style="display:none" data-health-questionnaire-target="bodySymptomsModalValue"><%= @link %></p>
    <%= render partial: "shared/body_symptoms_zoom", locals: {side: @side} %>
  </div>
<% end %>

app/views/bodies/index.html.erb
<div class="health-questionnaire-page" data-controller="health-questionnaire">
  <div class="health-questionnaire-page-intro">
      <h2 class="questionnaire-page-title title-health-questionnaire text-4xl">Questionnaires</h2>
  </div>

  <ul>
  <% @bodies.each_with_index do |body, index| %>
    <li class="body-list-item m-4 p-4 rounded-lg" data-health-questionnaire-target="bodySymptomsSvgDezoom" data-list="<%= body.parts %>">
    <h2>body <%= index %></h2>
      body parts: <%= body.parts %>
      <div class="flex justify-center">
        <% body_sides = ["front", "back"] %>
        <% body_sides.each_with_index do |side, index| %>
          <div class="perso-<%=side%> perso">
            <p><%= side %></p>
            <%= inline_svg_tag "body/dezoom_body_#{side}.svg", class: "dezoomed-body-svg h-64" %>
          </div>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>
<%= link_to "New Body", new_body_path, class: "body-symptoms-selector-submit h-14 w-80 rounded-lg text-white text-sm leading-4 mt-2 w-11/12 max-w-[31.25rem] rounded-xl h-9 flex justify-center items-center flex-row mx-auto mb-10" %>
</div>

app/views/bodies/new.html.erb
<div class="health-questionnaire-page">
  <div class="health-questionnaire-page-intro">
      <h2 class="questionnaire-page-title title-health-questionnaire">Questionnaire de santé</h2>
  </div>

  <%= form_with(model: @body, class: "form-questionnaire") do |f| %>
    <div class="questionnaire-container-inner" data-controller="health-questionnaire validations">
      <div id="link-to-body-symptoms-modal" class="questionnaire-fifth-part questionnaire-section">
        <h4 class="question-title" id="body_symptoms_title">Indique les endroits où tu as des symptômes</h4>
        <div class="perso-container flex justify-evenly h">
          <%= f.text_field :parts,
            hidden: true,
            data: {
              health_questionnaire_target: "outputBodySymptoms",
              validations_target: "bodySymptomsInput"
            },
            value: ""
          %>
          <% body_sides = ["front", "back"] %>
          <% body_sides.each_with_index do |side, index| %>
            <div class="perso-<%=side%> perso flex flex-col items-center">
              <p><%= side %></p>
              <%= link_to body_symptoms_path(side), class: "link-to-body-symptoms-modal", data: { turbo_method: :post, turbo_frame: "questionnaire_perso_#{side}_modal" } do %>
                <%= inline_svg_tag "body/dezoom_body_#{side}.svg", class: "dezoomed-body-svg h-80 w-40"  %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>



      <div class="submit-questionnaire">
        <%= f.submit value: "Valider", data: { action: "click->validations#checkIfChecked"}, class: "body-symptoms-selector-submit h-14 w-80 rounded-lg text-white text-sm leading-4 mt-2 w-11/12 max-w-[31.25rem] rounded-xl h-9 flex justify-center items-center flex-row" %>
      </div>

      <div id="body_symptoms_modal" data-health-questionnaire-target="bodySymptomsModal">

      </div>

    </div>
  <% end %>
</div>

app/views/bodies/show.html.erb
<div>toto</div>

app/views/layouts/_header.html.erb
<header id="header" class="wmbt-header w-screen h-20">
  <nav role="navigation" aria-label='quick-access'>
    <ul>
      <li>
        <a href="#main" id="skipToMain" class="skiptocontent">main</a>
      </li>
      <li>
        <a href="#footer" id="skipToFooter" class="skiptocontent">footer</a>
      </li>
    </ul>
  </nav>
  <div class='flex justify-between py-2 max-w-7xl mx-auto h-full'>
    <div class="wmbt-header__header-logo my-auto text-4xl">wmbt</div>
    <div class="display-options flex">
        <div class='language-toggle w-20 h-auto flex'>
          <button
            class="h-full m-auto"
            aria-label="sombre"
          >
            sombre
          </button>
        </div>
        <div class='dark-mode-toggle w-12 h-auto flex'>
          <button
            class="h-full m-auto"
            aria-label="langage"
          >
            fr
          </button>
        </div>
      </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BodyPartsSelector</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css2?family=Arvo&family=Quicksand:wght@300;600;700;900&display=swap', media: 'all', 'data-turbolinks-track' => true %>
  </head>
  <%= render "layouts/header" %>
  <body class="body-parts__body">
    <main class="container mx-auto mt-28 px-5 flex justify-center">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_body_symptoms_zoom.html.erb
<div class="body-symptoms-modal h-screen flex justify-center items-center flex-col" data-controller="body-parts-modal">
  <div class="model-body-symptoms-selector h-4/5">
    <%= inline_svg_tag "body/zoom_body_#{side}.svg"  %>
  </div>
  <%= button_tag(type: 'button', class: "body-symptoms-selector-submit h-14 w-80 rounded-lg text-white text-sm leading-4 mt-2 w-11/12 max-w-[31.25rem] rounded-xl h-9 flex justify-center items-center flex-row", data: {action: "click->health-questionnaire#close"}) do %>
    <%= "Continuer"%>
  <% end %>
</div>